openjdk-binary-native: fix build without x11 in DISTRO_FEATURES
prevents the follwing build error:

ERROR: Nothing RPROVIDES '<dep>'
<dep> was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)

Signed-off-by: Jermain Horsman <jermain.horsman@nedap.com>